[package]
name = "gcode-bandage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
nom = "7.1.3"
rfd = "0.13.0"
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
